services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    volumes:
      - ./backend/src:/app/src
    environment:
      - CHOKIDAR_USEPOLLING=true
      - CHOKIDAR_INTERVAL=100
    depends_on:
      drizzle:
        condition: service_completed_successfully
      postgres:
        condition: service_healthy
      mongo:
        condition: service_healthy
      storage:
        condition: service_started

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    volumes:
      - ./frontend/src:/app/src
    environment:
      - ORIGIN=http://localhost
      - CHOKIDAR_USEPOLLING=true
      - CHOKIDAR_INTERVAL=100
    depends_on:
      drizzle:
        condition: service_completed_successfully
      postgres:
        condition: service_healthy
      backend:
        condition: service_started

  caddy:
    volumes:
      - ./caddy/Caddyfile.dev:/etc/caddy/Caddyfile
