metadata_dir = "/var/lib/garage/meta"
data_dir = "/var/lib/garage/data"
db_engine = "lmdb"
replication_factor = 1
rpc_bind_addr = "[::]:3901"
rpc_public_addr = "storage:3901"

[s3_api]
s3_region = "garage"
api_bind_addr = "[::]:3902"

[admin]
api_bind_addr = "[::]:3903"
admin_token = "5d1ceeb5d94e65e32ad1f47596cc1d84a73acb722325b15bf973aa0f2c1e363d"
