metadata_dir = "/var/lib/garage/meta"
data_dir = "/var/lib/garage/data"
db_engine = "lmdb"
replication_factor = 1
rpc_bind_addr = "[::]:3901"
rpc_public_addr = "storage:3901"

[s3_api]
s3_region = "garage"
api_bind_addr = "[::]:3902"

[admin]
api_bind_addr = "[::]:3903"
admin_token = "f948ffb31bb9a82871b3454c876aaa543bbc01a04fdd0999d686c508b0039ef6"
